name: Build documentation

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build documentation
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "14.0"
      - name: Build
        env:
          platform: ${{ 'iOS Simulator' }}
        run: |
          device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//"`
          xcodebuild docbuild -scheme Placement -derivedDataPath $GITHUB_WORKSPACE/build -destination "platform=$platform,name=$device"
      - name: Clone swift-docc
        run: git clone https://github.com/apple/swift-docc.git
      - name: Setup DOCC_HTML_DIR
        run: export DOCC_HTML_DIR="$(dirname $(xcrun --find docc))/../share/docc/render"
      - name: Build swift-docc
        run: cd swift-docc && swift build
      - name: Run swift-docc
        run: cd swift-docc && swift run docc process-archive transform-for-static-hosting ../build/Build/Products/Debug-iphonesimulator/Placement.doccarchive --output-path ../build/Docs
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/Docs
